export const collapsiblesInitial = {
  "Are you looking for a centre or individual?": {
    NGO: false,
    "Licensed Psychologist": false,
  },
  Location: {
    options: [
      { Akkar: false },
      { Aley: false },
      { Baabda: false },
      { Baalbek: false },
      { Batroun: false },
      { Beirut: false },
      { "Bint Jbeil": false },
      { Bsharri: false },
      { Byblos: false },
      { Chouf: false },
      { Hermel: false },
      { Keserwan: false },
      { "Miniyeh-Danniyeh": false },
      { Nabatieh: false },
      { Rashaya: false },
      { Sidon: false },
      { Tripoli: false },
      { Tyre: false },
      { "Western Beqaa": false },
      { Zahlé: false },
      { Zgharta: false },
      { "Across Lebanon": false },
      { Online: false },
    ],
  },
  "Who is this for? ": {
    "Toddlers / Preschoolers (0-6 years)": false,
    "Children (6-12 years)": false,
    "Teenagers / Adolescents (13-19 years)": false,
    Adults: false,
    "Elders (65+)": false,
    Couples: false,
  },
  "What can we help you with?": {
    Anxiety: false,
    "Childhood Trauma Therapy": false,
    Depression: false,
    "Disaster / Terrorism": false,
    "Domestic Violence": false,
    "Expressive Trauma Therapy": false,
    "Expressive Trauma Therapy": false,
    Hypnotherapy: false,
    "Life / Personal Coaching": false,
    "Life Transition & Adjustment Issues": false,
    "Memory loss Therapy": false,
    "Pain Management": false,
    "Parenting during Trauma": false,
    "Pharmacotherapy (medication)": false,
    Psychoeducation: false,
    PTSD: false,
    "Sexual Abuse": false,
    "Sleeping Disorders": false,
    "Stress Management": false,
    "Substance Abuse": false,
    Suicide: false,
    "Trauma Group support": false,
    "Trauma-focused cognitive behavioral therapy": false,
  },
  "Preferred languages": {
    Arabic: false,
    French: false,
    English: false,
    Spanish: false,
    "Sign language": false,
  },
  Appointments: {
    Virtual: false,
    "In person": false,
  },
  Price: {
    "Free service": false,
  },
  "Name of mental health professional or organization": {
    text: "",
  },
};
