apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-typescript-deployment
  labels:
    app: node-typescript-app
spec:
  selector:
    matchLabels:
      app: node-typescript-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-typescript-app
    spec:
      containers:
        - name: app
          image: <DOCKER_IMAGE>
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: node-typescript-app
  labels:
    app: node-typescript-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: node-typescript-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: node-typescript-app
spec:
  to:
    kind: Service
    name: node-typescript-app
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
