name: Prod deploy

on:
  release:
    types: [published]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  ICR_NAMESPACE_PROD: lrn-registry-prod
  ICR_NAMESPACE_TEST: lrn-registry-test
  REGISTRY_HOSTNAME: de.icr.io
  IMAGE_NAME_PROD: lrn-app-prod
  IMAGE_NAME_TEST: lrn-app
  PORT: 3000

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f container-registry
          ibmcloud plugin install code-engine

      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g LRN
          ibmcloud cr region-set "${IBM_CLOUD_REGION}"
          ibmcloud cr login

      # Pull the candidate image from test
      - name: Pull the image from test ICR
        run: |
          docker pull $REGISTRY_HOSTNAME/$ICR_NAMESPACE_TEST/$IMAGE_NAME_TEST:$GITHUB_SHA
          
      # Tag the candidate image to be ready for prod
      - name: Tag the image from test to be ready for prod
        run: |
          docker tag $REGISTRY_HOSTNAME/$ICR_NAMESPACE_TEST/$IMAGE_NAME_TEST:$GITHUB_SHA $REGISTRY_HOSTNAME/$ICR_NAMESPACE_PROD/$IMAGE_NAME_PROD:${GITHUB_REF##*/}
      
      # Push the image to IBM Container Registry
      - name: Push the image to prod ICR
        run: |
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE_PROD/$IMAGE_NAME_PROD:${GITHUB_REF##*/}

      # Deploy to Code Engine
      # - name: Deploy to Code Engine
      #   run: |
      #     ibmcloud target -r eu-de
      #     ibmcloud ce project select -n LRN-web-app
      #     ibmcloud ce application update --name=lrn-test --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA
