name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Run Unit Tests

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd web-app && npm ci
      - run: cd web-app && npm test -- --watchAll=false
      - run: cd data-service && npm ci
      - run: cd data-service && npm test -- --watchAll=false
